# Generated by Django 2.0.2 on 2018-03-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(default='0', max_length=1, verbose_name='性別')),
                ('account', models.CharField(max_length=20, verbose_name='帳號')),
                ('password', models.CharField(max_length=50, verbose_name='密碼')),
                ('born', models.DateField(verbose_name='生日')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='信箱')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='電話')),
                ('country', models.CharField(blank=True, default='TW', max_length=5, verbose_name='國家')),
                ('city', models.CharField(blank=True, default='Taipei', max_length=30, verbose_name='城市')),
                ('area', models.CharField(blank=True, default='', max_length=30, verbose_name='區域')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='地址')),
                ('zip', models.CharField(blank=True, default='', max_length=5, verbose_name='郵遞區號')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
